DELETE http://localhost:3003/api/blogs/662080257a37297c53997a23
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjY2MjA2MmI5N2Q4NmZmNGU5MTdmZWMxMSIsImlhdCI6MTcxMzQwODY1MSwiZXhwIjoxNzEzNDEyMjUxfQ.UXGr9m8rVZ2J3rj_yeoLiaS_82kk2PPUpNG1AstH7fU